Update download.py
This change will prevent the below error which is an encoding error
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 803: character maps to <undefined>